classDiagram
direction LR

NoteIndex --> NoteAndAccidental 
NoteAndAccidental --> NoteInText 
NoteAndAccidental --> NoteInVex 
NoteInVex --> NoteRenderer 

SelectedNotes --> KeyboardLinear
SelectedNotes --> KeyboardCircular
SelectedNotes --> NotesRenderer

