flowchart LR

NI["note indices"]
NA["NoteAndAccidental"]
NT["Notes In Text"]
NV["Notes In Vex notation"]
CM["ChordMatch"]
CD["ChordDefinition"]
CIM["Chord Interval Manager"]
II["Inversion Index"]
NG["Note Grouping"]
OI["Offsets"]
AT["AccidentalType"]

RNM["Roman Numeral with modifiers"]
RNS["Roman Numeral String (pure)"]
RC["Roman Chord"]
RO["Roman Ordinal"]

AC["Absolute Chord"]
MK["Musical Key"]
CI["Chromatic Index"]
CT["Chord Type"]

AC --> NA
CM --> CD  
CD --> NG
CD --> OI
CIM --> CD
CM -.-> NT
CM -.-> NI
CM --> II
NI -.-> NA 
NA -.-> NT 
NA -.-> NV 

RC -.-> CT
RC -.-> AT
RC --->|MK| AC
RNS ---> |getOrdinal| RO
RO ---> |getOrdinalAsRomanString| RNS

RC ---> |getString| RNM
RNM ---> |getRomanChord| RC

CI ---> NA
NA -.-> AT


