flowchart LR

NI["note indices"]
NA["NoteAndAccidental"]
NT["Notes In Text"]
NV["Notes In Vex notation"]
CM["ChordMatch"]
CD["ChordDefinition"]
II["Inversion Index"]
NG["Note Grouping"]
OI["Offsets"]
AC["Accidental"]

AC --> NA
CM --> CD  
CD --> NG
CD --> OI
CM -.-> NT
CM -.-> NI
CM --> II
NI -.-> NA 
NA -.-> NT 
NA -.-> NV 

